"""
Article configuration

User input for article generation.
"""
from dataclasses import dataclass
from typing import Optional
from pathlib import Path
import yaml


@dataclass
class ArticleConfig:
    """Configuration for article generation (user input)"""
    title: str
    target_audience: str
    tone: str = "ekspercki, ale naturalny i rozmowny"

    # Generated by AI during process
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None

    @classmethod
    def from_yaml(cls, config_path: Path) -> 'ArticleConfig':
        """Load configuration from YAML file"""
        with open(config_path, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)

        return cls(
            title=data['title'],
            target_audience=data['target_audience'],
            tone=data.get('tone', "ekspercki, ale naturalny i rozmowny"),
            meta_title=data.get('meta_title'),
            meta_description=data.get('meta_description')
        )

    def to_yaml(self) -> str:
        """Convert configuration to YAML format"""
        data = {
            'title': self.title,
            'target_audience': self.target_audience,
            'tone': self.tone
        }

        if self.meta_title:
            data['meta_title'] = self.meta_title
        if self.meta_description:
            data['meta_description'] = self.meta_description

        return yaml.dump(data, allow_unicode=True, default_flow_style=False, sort_keys=False)

    def save(self, config_path: Path) -> None:
        """Save configuration to YAML file"""
        config_path.parent.mkdir(parents=True, exist_ok=True)
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write(self.to_yaml())
